### ISSUE TITLE
Not working with latest python and slurm versions

### ISSUE THREAD

**Issue by alansill** [shahzebsiddiqui/jobstats#1] opened 2021-02-28 05:51 UTC
I tried this, changing the code to work with python 3 by wrapping all print commands in () and adding the .decode('utf-8') to the subprocess.check_output command, but still am not seeing meaningful output when running under python 3.6.8 and slurm 2.11.03.

Let me know if I can provide more details but meanwhile wanted to see if you are still using and maintaining this tool Thanks!

**Comment by shahzebsiddiqui** [comment] 2021-02-28 18:33
Hi @alansill, thanks for trying out the tool. I see the code-base is in python 2.x and this was developed in 2018 at that time there wasn't a need to move to python 3.x but now I see this needs to be refactored since python 2.x is basically dead. Yes, I have this tool deployed on Cori and part of the docs https://docs.nersc.gov/jobs/monitoring/#jobstats so any changes will imply slight update to docs. Now that i think of it, our docs need to be updated since it doesn't mention python version. This tool won't work with python 3.x.

If you have some changes your would like to share, please feel free to open a PR and i'd be happy to review it.  I will spend some time to add some documentation. I don't think i can have regression tests against this tool since it's not easy to test this in github workflow without a slurm cluster. What i have is some basic tests in buildtest https://github.com/buildtesters/buildtest-cori/blob/devel/buildspecs/tools/jobstats.yml to see if tool is working as expected. At Cori we are using slurm version `20.02.6` so I don't want to be in business of supporting different slurm versions. I'd prefer the tool is working with latest version, if there are known issues with older version of slurm we can just document it.

**Comment by shahzebsiddiqui** [comment] 2021-02-28 18:36
Please share the error you are receiving. If It's utf-8 error perhaps we can try setting `LANG="utf-8"`. I won't know until i see error.

**Comment by matthdan** [comment] 2021-04-12 13:03
Hello all, 

This #2 should help you! This works for me on python 3.6.8, with slurm version **18.08.8** & **20.02.1**

Cheers,
Matth

**Comment by shahzebsiddiqui** [comment] 2021-04-16 15:23
closing this issue thank you @matthdan for your contribution.  I will cut a release and update the docs. I am glad this tool is useful :)

**Closed as completed by shahzebsiddiqui** 2021-04-16 15:23 UTC
